---
title: "hw_week4"
author: "Me"
date: "11 05 2020"
output: html_document
---

## Loading and preprocessing the data

 ```{r, echo = TRUE}
pacman::p_load(tidyverse,lubridate)

df <- readr::read_csv("H:\\LITERATURA_i_POBRANE\\R_kurs\\Cursera R\\Reproducible_resarch_week_4\\repdata_data_StormData.csv.bz2")
table(df$EVTYPE)
unique(df$EVTYPE)

df1 <- df %>% select(EVTYPE, FATALITIES, INJURIES) 

df_dead <- df1 %>% 
    group_by(EVTYPE) %>%
    summarise(total = sum(FATALITIES)) %>% 
    mutate(dead_or_injured = "dead") %>% 
    filter(total > 0)

summary(df_dead) 

df_dead_small <- df_dead %>% 
    filter(total < quantile(total, 0.75)) %>% 
    summarise(EVTYPE = "other" ,total = sum(total), dead_or_injured = "dead")

df_dead_large <-  df_dead %>% filter(total >= quantile(total, 0.75))
  
    
df_injured <- df1 %>% 
    group_by(EVTYPE) %>%
    summarise(total = sum(INJURIES)) %>% 
    mutate(dead_or_injured = "injured") %>% 
    filter(total > 0)

summary(df_injured) 

df_injured_small <- df_injured %>% 
    filter(total < quantile(total, 0.75)) %>% 
    summarise(EVTYPE = "other" ,total = sum(total), dead_or_injured = "injured")

df_injured_large <-  df_injured %>% filter(total >= quantile(total, 0.75))


df2 <- rbind(df_dead_small, df_dead_large, df_injured_small, df_injured_large)


df2$EVTYPE <- factor(df2$EVTYPE , levels = unique(df2$EVTYPE))
 
ggplot(df2)+geom_col(aes(x=EVTYPE, y=total, fill= dead_or_injured), width = 2)+
        coord_cartesian(ylim = c(0, 100), xlim = c(0, 1500))+
        coord_flip()


```

## Including Plots

You can also embed plots, for example:

```{r pressure, echo=FALSE}
plot(pressure)
```

Note that the `echo = FALSE` parameter was added to the code chunk to prevent printing of the R code that generated the plot.
